[package]
name = "just-fetch"
version = "0.1.2"
authors = [ "varsity <varsity@duck.com>" ]
description = "A simple minimal neofetch alternative"
edition = "2021"

[dependencies]
arguments = "0.7.1"
ansi_rgb = "0.2.0"
rgb = "0.8.34"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
