[package]
name = "just-fetch"
version = "0.1.1"
authors = [ "varsity <varsity@duck.com>" ]
description = "A simple minimal neofetch alternative"
edition = "2021"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
