[package]
name = "just-fetch"
version = "0.1.0"
authors = [ "varsity <varsity@duck.com>" ]
description = "A simple minimal neofetch alternative"
edition = "2021"

[dependencies]
arguments = "*"
ansi_rgb = "*"
libc = "*"
rgb = "*"

[profile.release]
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
