[package]
name = "just-fetch"
version = "0.1.3"
authors = [ "varsity <varsity@duck.com>" ]
description = "A simple minimal neofetch alternative"
edition = "2021"

[dependencies]
pretty-bytes = "*"
arguments = "*"
byte-unit = "*"
ansi_rgb = "*"
libc = "*"
rgb = "*"

[profile.release]
overflow-checks = false
panic = "abort"
opt-level = 3
strip = true
lto = "fat"
