[package]
name = "just-fetch"
version = "0.1.4"
authors = [ "varsity <varsity@duck.com>" ]
description = "A simple minimal neofetch alternative"
edition = "2021"

[dependencies]
lxinfo = { git = "https://github.com/vars1ty/lxinfo.git" }
lazy-regex = "3.0.2"
colorful = "0.2.2"
arguments = "*"
ansi_rgb = "*"
rgb = "*"

[profile.release]
overflow-checks = false
codegen-units = 1
opt-level = "z"
strip = true
lto = "fat"
